### ISSUE TITLE
Disabled checkboxes's label opacity

### ISSUE THREAD

**Issue by uatisdeproblem** [iter-idea/IDEA-Ionic8-extra#64]
As of today, there is no way of forcing the style of a disabled checkbox in `.viewMode`, so that the label doesn't look opaque. 

_Let's wait for a change to arrive in Ionic to fix this._

**Comment by uatisdeproblem** [comment]
Ionic added a way to set the style: https://ionic.io/blog/announcing-ionic-7-6

```css
ion-checkbox::part(label) {
  padding: 10px;
}
```
